### ISSUE TITLE
Check the protection option at the beginning of onHopperMoveItem

### ISSUE THREAD

**Issue by SrBedrock** [DevCyntrix/death-chest#48]
Ignore onMoveHopperItem if the death chest protection option is disabled.

Config:
```yaml
# This option protects the death chest against thieves if the player has the specific permission and the thief
# not the bypass permission.
chest-protection:
  enabled: false
  permission: 'deathchest.thiefprotected'
  bypass-permission: 'deathchest.thiefprotected.bypass'
  # To enable the expiration set the number to number greater than 0. The unit of this variable is seconds.
  expiration: 0
  # On this website you can find a list of all sounds which is implemented in SpigotMC
  # @see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # If you want to disable the sound or the message, you can delete these options
  sound: BLOCK_CHEST_LOCKED;1.0;1.0
  message: |-
    &cYou are not permitted to open this chest
```

Spark:
[![image](https://github.com/DevCyntrix/death-chest/assets/51332006/dd2b34fc-fa25-4139-9ddf-ec523bded735)](https://i.imgur.com/n6rlXkh.png)
