### ISSUE TITLE
[Suggestion] Let the player know when the chest is getting closer to expires/disappear

### ISSUE THREAD

**Issue by cupangafk** [DevCyntrix/death-chest#50]
the idea is to notify player every `n` seconds that the chest is gonna be expires 

for example
```yaml
expiration: 1800 # about 30 min
notify-every: 300 # 5 minutes
notify-message: Your death chest gonna disappeared in {time} hurry up
```

or we can set up our custom time for example
```yaml
notify:
  600: Your death chest gonna be disappeared in 10 min # alert the player 10 minutes before the chest expires
  300: Hurry up, 5 min again !!! # alert the player 5 minutes before the chest expires
  -1: farewell to your item :( # when the chest disappeared
```
